{{ if .Values.bootnode.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-boot-node-init-script
  labels:
    app: boot-node
    app.kubernetes.io/name: boot-node
    helm.sh/chart: {{ include "daily-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  entrypoint.sh: |-
    #!/bin/bash
    DATA_PATH=/root/.daily
    WALLET_PATH=$DATA_PATH/wallet_daily.json

    echo "Generating wallet..."
    INDEX=${HOSTNAME##*-}
    KEY="BOOT_NODE_KEY_${INDEX}"
    VRF="BOOT_NODE_VRF_${INDEX}"

    KEY="${!KEY}"
    VRF="${!VRF}"

    dailyd --command config \
      --node-secret ${KEY} \
      --vrf-secret ${VRF} \
      --wallet $WALLET_PATH
{{- end }}
