{{ if .Values.node.enabled }}
{{- if .Values.node.serviceMonitor.enabled  }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  {{ include "daily-node.fullname" . }}
  labels:
    name: daily-node
    app.kubernetes.io/name: daily-node
    helm.sh/chart: {{ include "daily-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: daily-node
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace | quote }}
  endpoints:
    - honorLabels: true
      path: /metrics
      port: metrics
    - honorLabels: true
      path: /metrics
      port: metrics-indexer
{{- end }}
{{- end }}
