{{- if .Values.serviceAccounts.pythontester.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: python-tester
    app.kubernetes.io/name: {{ include "daily-node.name" . }}
    helm.sh/chart: {{ include "daily-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ include "daily-node.fullname" . }}-python-tester"
{{- end }}
